#!/usr/bin/env bash

set -eu

source "${HALCYON_TOP_DIR}/src.sh"


slug_post_build_hook () {
	local tag source_dir slug_dir
	expect_args tag source_dir slug_dir -- "$@"

	local data_dir hook_file
	data_dir="${source_dir}/.halcyon-magic/slug-post-build-hook-data"
	hook_file="${data_dir}/haste-compiler-0.4.3.slug-post-build-hook"

	halcyon deploy                                \
		--install-dir="${slug_dir}"           \
		--constraints-dir="${data_dir}"       \
		--sandbox-extra-libs="libbz2-dev"     \
		--slug-post-build-hook="${hook_file}" \
		"haste-compiler-0.4.3" || return 1
}


slug_post_build_hook "$@" || die
